### ISSUE TITLE
Set targetSdkVersion to 23, crash happend

### ISSUE THREAD

**Issue by CPPAlien** [BelledonneCommunications/linphone-iphone#101]
```
java.lang.ExceptionInInitializerError
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:324)
at java.lang.Class.forName(Class.java:285)
at org.linphone.core.LinphoneCoreFactory.instance(LinphoneCoreFactory.java:44)
at tw.com.chainsea.call.base.LinphoneManager.<init>(LinphoneManager.java:65)
at tw.com.chainsea.call.base.LinphoneManager.createAndStart(LinphoneManager.java:89)
at tw.com.chainsea.call.SipCallManager.<init>(SipCallManager.java:33)
```
I use the sdk download from the link below,
https://www.linphone.org/releases/android/linphone-android-sdk-latest.zip

if the targetSdkVersion was set to 22, everything is good. But if it's changed to 23, crash happened. Do you have any solutions to it, Thanks a lot.

**Comment by bagage** [comment]
This is an Android crash, not iOS.

**Comment by CPPAlien** [comment]
Sorry for that, but I cannot find issue entry in https://github.com/BelledonneCommunications/linphone-android, is that you guys closed the issue in this repo ?

**Comment by bagage** [comment]
Yes that was closed on purpose ; we have no time to handle it unfortunately. In the mean time issues on iOS are rare and valuable so I keep tracking them.

**Comment by CPPAlien** [comment]
so is there anyone still tracking android issues? Thank you.

**Comment by bagage** [comment]
The mailing list is the best place for that.
