### ISSUE TITLE
prepare.py fails with TypeError if cmake is missing on Linux

### ISSUE THREAD

**Issue by haxsaw** [BelledonneCommunications/linphone-iphone#102]
When trying to run prepare.py, I got the following stack trace:

```
haxsaw@maxwell:~/tmp/linphone-desktop$ ./prepare.py 
Traceback (most recent call last):
  File "./prepare.py", line 223, in <module>
    sys.exit(main())
  File "./prepare.py", line 218, in main
    preparator.show_environment_errors()
  File "submodules/cmake-builder/prepare.py", line 279, in show_environment_errors
    self.show_missing_dependencies()
  File "./prepare.py", line 158, in show_missing_dependencies
    " ".join(self.missing_dependencies.values())))
TypeError: sequence item 0: expected string, NoneType found
```
Stopping prepare inside show_missing_dependencies(), I can see that self.missing_dependencies has a key 'cmake' and associated value of None.

**Comment by bagage** [comment]
Fixed in master a560a0a, thanks.
