### ISSUE TITLE
excute prepare.py Fail  on Mac OX 10.11.6

### ISSUE THREAD

**Issue by duoleimi** [BelledonneCommunications/linphone-iphone#116]
`
./prepare.py i386`

```
Traceback (most recent call last):
  File "./prepare.py", line 355, in <module>
    sys.exit(main())
  File "./prepare.py", line 348, in main
    if preparator.check_environment() != 0:
  File "./prepare.py", line 170, in check_environment
    reterr |= prepare.Preparator.check_environment(self)
AttributeError: class Preparator has no attribute 'check_environment'
```

**Comment by ReisBenjamin** [comment]
please update to latest commit and re-open if not fixed.

Thanks
