### ISSUE TITLE
Getting OSError on running command "./prepare.py -c"

### ISSUE THREAD

**Issue by saurabhs70** [BelledonneCommunications/linphone-iphone#148]
umenit:linphone-iphone umenit$ ./prepare.py -c
Traceback (most recent call last):
  File "./prepare.py", line 355, in <module>
    sys.exit(main())
  File "./prepare.py", line 352, in main
    return preparator.run()
  File "submodules/cmake-builder/prepare.py", line 501, in run
    return self.clean()
  File "./prepare.py", line 137, in clean
    shutil.rmtree('liblinphone-sdk', ignore_errors=False)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 232, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 230, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link

**Comment by ReisBenjamin** [comment]
Hello,

Try to remove the liblinphone_sdk folder then re-run the commands.

**Comment by saurabhs70** [comment]
Hi @ReisBenjamin 
Thanks it worked.. appreciated
