### ISSUE TITLE
Unexpected keyword argument 'virtual_targets'

### ISSUE THREAD

**Issue by Valerio69** [BelledonneCommunications/linphone-iphone#76]
Just cloned the git, Running './prepare.py && make' and I got this error.

Traceback (most recent call last):
  File "./prepare.py", line 352, in <module>
    sys.exit(main())
  File "./prepare.py", line 343, in main
    preparator = IOSPreparator()
  File "./prepare.py", line 96, in __init__
    prepare.Preparator.__init__(self, targets, default_targets=['armv7', 'arm64', 'x86_64'], virtual_targets=virtual_targets)
TypeError: __init__() got an unexpected keyword argument 'virtual_targets'

I've HomeBrew installed and using iTerm. What am I doing wrong?

**Comment by Valerio69** [comment]
Seems I had this problem because I was downloading the git via HTTPS, once I changed it to Http the problem was fixed. Consider closed this issue.
